### ISSUE TITLE
cmp stderr printed when if one file is a prefix of the other is not colored

### ISSUE THREAD

**Issue by lizhenguo** [sickill/stderred#56]
From the `cmp` info pages, it says that 
>If one fle is a prefx of the other, cmp prints to standard error a message of the following form:  
`cmp: EOF on shorter-file`

For example, there are `file1.txt` and `file2.txt`:
file1.txt:
```
Hi My name is Himanshu
```
file2.txt:
```
Hi My name is Himanshu
Hi My name is Himanshu Arora
```
So when execute `cmp file1.txt file2.txt1`, it will print "cmp: EOF on file1.txt" to stderr, so it should be colored. But actually it haven't. 
When I test it with a program named [hilite](https://sourceforge.net/projects/hilite/?source=directory), which works well for this case.

**Comment by DanOlivier** [comment]
I think that the reason that `cmp` doesn't color the output, is because it calls `__fprintf_cmp` instead of just `fprintf`, which performs a system call rather than calling `fprintf`, which would be "captured" (and colored).

Note: this occurs when the target (i.e. `cmp` in this case) is compiled in release/optimized, and I could not get the compiler to resolve to `__fprintf_cmp` in debug with `-D_FORTIFY_SOURCE=2`). 

I got it to work by adding the following code:
```
int FUNC(__fprintf_chk)(FILE *fp, int flag, const char *format, ...) {
  va_list args;
  va_start(args, format);
  int result = FUNC(vfprintf)(fp, format, args);
  va_end(args);
  return result;
}
```
Not sure this is an elegant solution.

**Comment by lizhenguo** [comment]
Thank you!

**Comment by cehoffman** [comment]
Should be fixed now with @DanOlivier's PR
