### ISSUE TITLE
Not working in Mac OS X Mojave 10.14.6

### ISSUE THREAD

**Issue by byronaltice** [sickill/stderred#79]
I've tried this in zsh, bash, and sh, the color of stderr isn't changed at all.

I ran make, set the correct path in ~/.bash_profile, sourced it, and all stderr is still jsut the default color.

![image](https://user-images.githubusercontent.com/6363060/78388647-5c826f00-75af-11ea-8e14-336001b93958.png)
![image](https://user-images.githubusercontent.com/6363060/78388680-686e3100-75af-11ea-90f9-31453bd1cf05.png)

**Comment by scinos** [comment]
Same in 10.15.7.

Seems to work for `ls`, but not for `cat`:

![image](https://user-images.githubusercontent.com/975703/99049840-9ed54b00-2597-11eb-835d-4d298a65a1b8.png)

**Comment by cehoffman** [comment]
This can't be fixed because it is a feature in later OS X releases called System Integrity Protection (SIP). It disallows modification of programs and libraries in certain paths on the filesystem. If you move the binaries somewhere else support for the darwin `write_nocancel` system call could be added.

<img width="483" alt="Screen Shot 2021-02-26 at 1 02 14 AM" src="https://user-images.githubusercontent.com/27545/109267357-0cb42400-77cf-11eb-99a2-9ac9eb104dab.png">

Installing the GNU coreutils from homebrew and adding the gnubin directory to your path solves the issue.

@scinos The difference you have there is because the `ls` you were using was from GNU and cat from BSD.
